# You must create an API in kong pointing to this service and tied to /.well-known/acme-challenge
# it will always be inaccessible as certbot standalone is the http server, and only exists while
# it's trying to acquire certificates
apiVersion: v1
kind: Service
metadata:
  name: kong-certbot-agent
spec:
  type: ClusterIP
  ports:
  - name: certbot
    port: 80
    targetPort: 80
    protocol: TCP
  - name: certbot-ssl
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: kong-certbot
---
# Make sure you edit your config below at the environment vars
# Take note of the namespace below, and change as needed
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-certbot-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-certbot
    spec:
      containers:
      - name: runtime
        image: phpdockerio/kong-certbot-agent:latest
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        env:
          - name: TERM
            value: linux
          - name: KONG_ENDPOINT
            value: https://gateway-kong-admin.default.svc.cluster.local:8444
          - name: EMAIL
            value: orie@transmute.industries
          - name: DOMAINS
            value: transmute.live,kong.transmute.live,ipfs.transmute.live