matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - MINIKUBE_VERSION=v0.25.2
        - USE_VOX=n
        - MINIKUBE_MEMORY=7777
        - MINIKUBE_CPU=4
        - MINIKUBE_DRIVER=none
        - HELM_INSTALL_DIR=$HOME/.local/bin
        - NVM_DIR="$HOME/.nvm"
        - KUBE_VERSION=v1.9.0
      language: bash
      cache:
        directories:
        - $HOME/.local/bin
        - $HOME/.transmute
        - $HOME/.minikube
        - $HOME/.kube
        - /usr/local
        - .git
    #- os: osx
      #osx_image: xcode8.3
      #language: bash
      #cache:
        #directories:
        #- $HOME/.minikube
        #- $HOME/.transmute
        #- $HOME/.kube
      #env:
        #- CHANGE_MINIKUBE_NONE_USER=true
        #- MINIKUBE_VERSION=v0.25.2
        #- USE_VOX=n

language: node_js
node_js:
  - "8"

before_script:
# Download kubectl, which is a requirement for using minikube.
# Download minikube.
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh .ci/linux_before_install.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci/mac_before_script.sh; fi
- bash -l -c "echo PATH=$HOME/.transmute/bin:$PATH >> $HOME/.bashrc"
- bash -l -c "echo PATH=$HOME/.local/bin:$PATH >> $HOME/.bashrc"
- if [[ ! -e "/usr/local/bin/kubectl" ]]; then curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBE_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/; fi
- if [[ ! -e "/usr/local/bin/minikube" ]]; then curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBE_VERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/; fi
- if [[ ! -e "$HOME/.local/bin/helm" ]]; then curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash; fi
- if [[ ! -e "$HOME/.local/bin/nsenter" ]]; then .ci/ubuntu-compile-nsenter.sh && sudo cp $HOME/nsenter/util-linux-2.30.2/nsenter $HOME/.local/bin && chmod +x $HOME/.local/bin/nsenter; fi
- sudo cp $HOME/.local/bin/nsenter /usr/bin/nsenter
- bash -l ./bootstrap
- minikube start --vm-driver=none --kubernetes-version=$KUBE_VERSION
# Fix the kubectl context, as it's often stale.
- minikube update-context
# Wait for Kubernetes to be up and ready.
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

script:
- env
- PATH=$HOME/.transmute/bin:$PATH which kubectl
- PATH=$HOME/.transmute/bin:$PATH which minikube
- bash -l -c "which npm"
- bash -l -c "which node"
- bash -l -c "node -v"
- bash -l -c "npm -v"
- bash -l -c "which ngrok"
- bash -l -c "which helm"
- bash -l -c "which nsenter"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -l .ci/linux_script; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci/mac_script.sh; fi

- bash -l -c "kubectl get services"
- bash -l -c "kubectl get pods"
- bash -l -c "npm i"
- bash -l -c "w8s/generic.w8 ganache default"

- pwd
- cd $TRAVIS_BUILD_DIR
- pwd
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -l ./scripts/spin-up-minkube.sh; fi
