matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - USE_VOX=n
      cache:
        directories:
        - $HOME/.minikube
        - $HOME/.transmute
        - $HOME/.kube
    - os: osx
      osx_image: xcode7.2
      cache:
        directories:
        - $HOME/.minikube
        - $HOME/.transmute
        - $HOME/.kube
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - USE_VOX=n

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh .ci/linux_before_install.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci/mac_before_script.sh; fi
- bash -l ./bootstrap

script:
- env
- PATH=$HOME/.transmute/bin:$PATH which kubectl
- PATH=$HOME/.transmute/bin:$PATH which minikube
- which ngrok
- which helm
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh .ci/linux_script.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci/mac_script.sh; fi
