#!/bin/bash
# Installs minikube, kubectl, and transmute into a minikube cluster
: ${TRANSMUTE_RELEASE:='master'}
: ${TRANSMUTE_DIR:=$HOME/.transmute}
: ${TRANSMUTE_BIN:=$TRANSMUTE_DIR/bin}
: ${VERBOSITY:=0}
: ${HELM_INSTALL_DIR:=$TRANSMUTE_BIN}
: ${MY_KUBE_VERSION:=v1.9.6}
: ${FIX_DOTFILES:= "true"}
: ${NVM_DIR_ADDS:= "true"}
: ${NVM_VERSION:='0.33.9'}
: ${USE_VOX:=y}

mkdir -p $TRANSMUTE_DIR
cd $TRANSMUTE_DIR

pwd
echo test > test
cat test
rm test
