
export const WEB3_CONNECTION_REFUSED = 'WEB3_CONNECTION_REFUSED';
export const WEB3_CONNECTION_SUCCESS = 'WEB3_CONNECTION_SUCCESS';
export const WEB3_ACCOUNTS = 'WEB3_ACCOUNTS';
export const SELECT_WEB3_ACCOUNT = 'SELECT_WEB3_ACCOUNT';
export const IPFS_CONNECTION_REFUSED = 'IPFS_CONNECTION_REFUSED';
export const IPFS_CONNECTION_SUCCESS = 'IPFS_CONNECTION_SUCCESS';
export const RECEIVE_WEB3_ACCOUNTS = 'RECEIVE_WEB3_ACCOUNTS'
export const DEBUG_SETTINGS_UPDATED = 'DEBUG_SETTINGS_UPDATED'

export const Constants = {
  WEB3_CONNECTION_REFUSED,
  WEB3_CONNECTION_SUCCESS,
  WEB3_ACCOUNTS,
  SELECT_WEB3_ACCOUNT,
  IPFS_CONNECTION_REFUSED,
  IPFS_CONNECTION_SUCCESS,
  RECEIVE_WEB3_ACCOUNTS,
  DEBUG_SETTINGS_UPDATED
}